name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@31.3.0
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: kor
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -f nilla.nix systems.nixos.kor-t14.result.config.system.build.toplevel
    - run: nix build -f nilla.nix systems.home."lk@kor-t14".result.activationPackage
    # - run: nix-shell --run "echo OK"
